controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: '{_locale}/admin'
    controller: App\Controller\Admin\AdminController::index
